### ISSUE TITLE
Make dashboard app compatible with PHP 7

### ISSUE THREAD

**Issue by ungesundes-halbwissen** [dehnhardt/nc_dashboard#2]
I can run the dashboard app flawlessly with PHP 7. Info.xml s just missing the acurate PHP max version which is still set to 5.6.

**Comment by dehnhardt** [comment]
which version should I set? Do we need a max php version at all? Can you check if it's working without a max php version...
[edit]
Sorry, I can check on my own...
...no php max version needed - so deleted the attribute
John, coud you please check if it works for you.

**Comment by dehnhardt** [comment]
As John stated in the [Nextcloud Forum](https://help.nextcloud.com/t/dashboard-for-nextcloud-by-flost-and-holger-was-anyone-in-for-an-overview-dashboard-start-page-app/1248/76?u=holger_dehnhardt), the issue is resolved.
